### ISSUE TITLE
Missed acknowledgments for the code and pictures

### ISSUE THREAD

**Issue by d-eremeev** [JaswanthBadvelu/Reinforcement-Learning-CVRP#1]
If you use the code, pictures and general structure from other people's work (paper: https://arxiv.org/abs/2002.03282, code: https://github.com/d-eremeev/ADM-VRP in this case), there is a common practice to mention it in acknowledgments and references in your work.

**Comment by JaswanthBadvelu** [comment]
Hello d-eremeev sorry for the delay, I provided Acknowledgements to your code and gave references to the paper. If you have any more issues with the references please let me know I will change accordingly.
